name: 'CI: Codecov'

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  CodeCov:
    name: Execute Codecov
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout the repository and commit
        uses: actions/checkout@v3
        with:
            submodules: 'recursive'
            fetch-depth: 0

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Generate coverage report
        run: |
          pip install pytest
          pip install pytest-cov

      - name: Setup Python path on Linux
        if: startsWith(matrix.os,'ubuntu')
        run: |
          PYTHONPATH=$(pwd):$PYTHONPATH
          export PYTHONPATH
          pytest --cov=./ --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          flags: unittests
          verbose: true
