name: 'CR: Commentator Pytest Coverage'

on:
  push:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Comment PyTest coverage report on PR
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout the repository and commit
        uses: actions/checkout@v3
        with:
            submodules: 'recursive'
            fetch-depth: 0

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build coverage file
        run: |
          PYTHONPATH=$PYTHONPATH:$(pwd)
          export PYTHONPATH
          pytest --cache-clear --cov=./ tests/ > pytest-coverage.txt

      - name: Comment coverage
        uses: coroo/pytest-coverage-commentator@v1.0.2
