name: 'CR: Check project own script'

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    name: Execute Codecov
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout the repository and commit
        uses: actions/checkout@v3
        with:
            submodules: 'recursive'
            fetch-depth: 0

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check Encode # run the run.py to get the latest data
        run: |
          python ci/CheckEncode/check_encode.py
