name: 'Daily: Lock Inactive'

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  lock:
    name: Execute Codecov
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/stale@v6
        with:
          stale-issue-message: 'This issue is stale because it has been open 7 days with no activity. Remove stale label or comment or this will be closed in 7 days.'
          stale-pr-message: 'This PR is stale because it has been open 7 days with no activity. Remove stale label or comment or this will be closed in 7 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 7 days with no activity.'
          close-pr-message: 'This PR was closed because it has been stalled for 7 days with no activity.'
          days-before-issue-stale: 7
          days-before-pr-stale: 7
          days-before-issue-close: 7
          days-before-pr-close: 7
